alerts:
  - disabled: true
    rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - disabled: true
    rule: DEPLOYMENT_LIVE
databases:
  - engine: PG
    name: it-desk-postgres
    version: "12"
envs:
  - key: ADMIN_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:hPa2MnEQA9zBnAs+aLgg5hPK3wZUIx78:7GVMKmMUXcAKHK5yvmNryUXkWD29guzxO3ZFHHpbnGYDz/F/lXJVChaBWEKexdeE59ZS1T6B5b4dBI462GM=]
  - key: ADMIN_BOT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:OZJSrpsjdk4aO0kEMXqeSPHviVZeSKp3:6EKjH5KYCnkN50V6Nal0hquB7CdomNQEd5yo8owz8501uG4xv95CN5t66crs5F6+]
  - key: EXPERT_BOT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:G2AbR/sBD8rarv3YegcKhn73lXZv0Zfg:5AB/j1xvuV6Bz2hZo3ffr+bfofIa3Wh8M4v1/tiBfU8TarXFCTdSRb1bJdCKJu2L]
  - key: EXPERT_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:t3R/6sFWhkMjzRkKWy3rhscekd7RAhdp:F9DRXysjrmdwYI22aTLybs422/qWkdhcEUmW4srZOrN39LN88l0nbS6E1+Ah3aps7RCR9iQgNtjFmZNkwaI=]
  - key: ADMIN_CHAT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:zKytz2IECtLqH0sJg7aDBbWtA+qaaDMJ:k683GPWJ/z+tEtdfCKKa+tvMiBKMNc50Dut4EV+M]
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: it-desk-api
      match:
        path:
          prefix: /it-desk
    - component:
        name: calcom-cal-com
      match:
        path:
          prefix: /
name: it-desk
region: fra
services:
  - dockerfile_path: api/Dockerfile
    envs:
      - key: LOG_LEVEL
        scope: RUN_AND_BUILD_TIME
        value: INFO
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${it-desk-postgres.DATABASE_URL}
      - key: PG_HOSTNAME
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.HOSTNAME}
      - key: PG_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.PORT}
      - key: PG_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.USERNAME}
      - key: PG_DATABASE
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.DATABASE}
      - key: PG_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.PASSWORD}
    github:
      branch: main
      deploy_on_push: true
      repo: ppotseluev/it-desk
    health_check:
      failure_threshold: 6
      http_path: /healthcheck
      initial_delay_seconds: 10
      period_seconds: 5
      port: 54611
      timeout_seconds: 5
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    internal_ports:
      - 54611
    name: it-desk-api
    source_dir: /
  - envs:
      - key: NEXTAUTH_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:htO+ELzO/0PIdM3mKt5c9XC34nO+6qpa:QyIR3wTLVFnWkfuz17WN1I3vSPKViPQYrtzTOamjJRgiC716os4/AY30hJ8u76vPTQ6ZnpKhw2PyeFrI]
      - key: CALENDSO_ENCRYPTION_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:sXgaPspHyExgixxCPfgU0FrXi0RbcCfS:WPacNuVAOUak/tkP9BX0+4SC4ty2Z967wAxBpVhF1Kkal9EkbxPdFw6bMdY9HwgS]
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.DATABASE_URL}
      - key: DATABASE_DIRECT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${it-desk-postgres.DATABASE_URL}
      - key: NEXT_PUBLIC_WEBAPP_URL
        scope: RUN_AND_BUILD_TIME
        value: https://it-desk-c2jag.ondigitalocean.app
    health_check:
      failure_threshold: 10
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 2
    http_port: 8080
    image:
      registry: calcom
      registry_type: DOCKER_HUB
      repository: cal.com
      tag: latest
    instance_count: 1
    instance_size_slug: basic-xs
    name: calcom-cal-com
